# site title
title: Pines Cheng‘s Think

# github user
user: Pines-Cheng 

# issue repository
repository: think

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 8#d8885d9955386353ce5c815714dd8dd65e38841

# posts per page
perpage: 10


